setTimeout(function() {
	$(".animar-interno1").addClass("animated fadeInLeft");
}, 1200);
setTimeout(function() {
	$(".animar-interno2").addClass("animated fadeInLeft");
}, 1500)
setTimeout(function() {
	$(".animar-interno3").addClass("animated fadeInLeft");
}, 1800)